# Generated by Django 2.0.5 on 2018-06-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='location',
            field=models.CharField(default='download.zip', max_length=30),
        ),
        migrations.AddField(
            model_name='files',
            name='token',
            field=models.CharField(default='a6803dedfad548258fe252a7621492af', max_length=100),
        ),
    ]
