# Generated by Django 2.0.5 on 2018-06-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20180611_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='location',
            field=models.CharField(default='download', max_length=30),
        ),
    ]
